export const COPY = {
  appTitle: 'Onramp',
  tagline: 'The first step, and only the first step.',
  startLabel: 'What do you have to do?',
  startPlaceholder: 'Paste it exactly as your teacher wrote it.',
  startCta: 'Find my first step',
  startExamplesLabel: 'Or try one of these',
  stepDone: 'Done',
  stepDoneNext: 'Done, next step',
  stepSmaller: 'Smaller',
  stepWhy: 'Why this?',
  stepWhyClose: 'Close',
  stepBack: 'previous step',
  stepDuration: 'about {n} {unit}',
  stepStarted: 'you started',
  auditHeading: 'Why this step',
  auditFrom: 'This came from',
  auditAuthority: 'The checker, not the model, decides when a step is small enough.',
  auditSourceRules: 'Built by the rules engine.',
  auditSourceModel: 'Proposed by the model and accepted by the checker.',
  auditSourceRegated: 'The model proposed something the checker rejected, so the rules engine was used instead.',
  auditCriticHeading: 'Critic',
  auditCoachHeading: 'Coach',
  finishTitle: 'That is the whole thing, finished.',
  finishCta: 'Start something else',
  finishSend: 'Send this to someone',
  finishSendCopied: 'Copied',
  finishStartedOnce: 'You started once.',
  finishStartedMany: 'You started {n} times.',
  finishMedian: 'You started each step in about {n} seconds.',
  errorEmpty: 'Paste the task first and I will find a starting point.',
  toggleSpacing: 'Extra spacing',
  toggleFont: 'Monospace',
  shortcuts: 'Keyboard: D done, S smaller, W why',
  voiceStart: 'Speak your assignment',
  voiceStop: 'Stop',
  voiceListening: 'Listening',
  voiceUnavailable: 'Voice input is not available in this browser.',
  installTitle: 'Install Onramp on this device',
  installCta: 'Install',
  installDismiss: 'Not now',
  qrHeading: 'Or scan to open',
  qrAlt: 'QR code linking to this session',
} as const;

export const EXAMPLES = [
  '5 page essay on the causes of World War One, due Friday',
  'Read chapter 7 and take notes',
  'Study for the biology test on Monday',
] as const;
